apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: ansibleee-playbook-local
  namespace: openstack
spec:
  inventory: |
    all:
      hosts:
        localhost:
          ansible_connection: local
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  play: |
    - hosts: all
      gather_facts: false
      vars:
        cmd: "lsblk"
      tasks:
        - name: run command
          shell: "{{ cmd }}"
          register: cmd_out
        - name: show command output
          debug:
            msg: "{{ cmd_out.stdout }}"
