apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: deploy-nova
  namespace: openstack
spec:
  image: "quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest"
  playbook: "deploy-nova.yaml"
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
    - name: ANSIBLE_VERBOSITY
      value: "1"
    - name: NOVA_COMPUTE_CONTAINER_IMAGE
      value: "quay.io/tripleomastercentos9/openstack-nova-compute:current-tripleo"
    - name: LIBVIRT_CONTAINER_IMAGE
      value: "quay.io/tripleomastercentos9/openstack-nova-libvirt:current-tripleo"
  extraMounts:
    - volumes:
        - name: inventory
          configMap:
            name: inventory-configmap
        - name: ssh-key
          secret:
            secretName: edpm-ssh-key
            items:
              - key: ssh_private_key
                path: ssh_key
        - name: playbooks
          configMap:
            name: nova-playbooks
        - name: compute-configs
          configMap:
            name: compute-configs
      mounts:
        - name: inventory
          mountPath: /runner/inventory/inventory.yaml
          subPath: inventory.yaml
        - name: ssh-key
          mountPath: /runner/env/ssh_key
          subPath: ssh_key
        - name: playbooks
          mountPath: /runner/project/deploy-nova.yaml
          subPath: deploy-nova.yaml
        - name: compute-configs
          mountPath: /var/lib/openstack/config
