
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-configmap
  namespace: openstack
data:
  inventory.yaml: |
    allovercloud:
      children:
        overcloud:
            children:
              Compute:
                hosts:
                  nova-compute-1:
                    ansible_ssh_user: centos
                    ansible_host: console-openshift-console.apps.oks-dev.seanmooney.info
                    ansible_port: 30067
                    ctlplane_ip: 10.0.2.2
                    internal_api_ip: 10.0.2.2
                    tenant_ip: 10.0.2.2
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                vars:
                  chrony_ntp_servers:
                    - time1.google.com
                    - time2.google.com
