---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/status
  verbs:
  - get
  - patch
  - update
