---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - nova
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - nova/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - nova/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novacells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novacells/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novacells/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novanovncproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novanovncproxies/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novanovncproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/status
  verbs:
  - get
  - patch
  - update
