apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openstack-operator
spec:
  name: openstack-operator
  channel: alpha
  config:
    env:
    - name: WATCH_NAMESPACE
      value: openstack
  source: openstack-operator-index
  sourceNamespace: openstack
