apiVersion: nova.openstack.org/v1beta1
kind: NovaCell
metadata:
  name: novacell2-without-upcall-sample
spec:
  cellName: cell2
  secret: osp-secret
  passwordSelectors:
    service: NovaPassword
    # this cell will not support upcalls
    apiDatabase: null
    apiMessageBus: null
    cellDatabase: NovaCell2DatabasePassword
    cellMessageBus: NovaCell2MessageBusPassword
  serviceUser: nova
  keystoneAuthURL: http://keystone-internal-openstack.apps-crc.testing
  apiDatabaseUser: null
  # cell2 doesn't have access to the api DB
  apiDatabaseHostname: null
  apiMessageBusUser: null
  # cell2 doesn't have access to api message bus
  apiMessageBusHostname: null
  cellDatabaseUser: nova
  cellDatabaseHostname: openstack
  cellMessageBusUser: nova
  cellMessageBusHostname: default-security-context
  conductorServiceTemplate:
    cellName: cell2
    passwordSelectors:
      service: NovaPassword
      apiDatabase: null
      apiMessageBus: null
      cellDatabase: NovaCell2DatabasePassword
      cellMessageBus: NovaCell2MessageBusPassword
    serviceUser: nova
    keystoneAuthURL: http://keystone-internal-openstack.apps-crc.testing
    apiDatabaseUser: null
    apiDatabaseHostname: null
    apiMessageBusUser: null
    apiMessageBusHostname: null
    cellDatabaseUser: nova
    cellDatabaseHostname: openstack
    cellMessageBusUser: nova
    cellMessageBusHostname: default-security-context
    customServiceConfig: >
      # service config customization
      [DEFAULT]
      debug=True
    defaultConfigOverwrite:
      logging.conf: >
      # my custom logging configuration
    containerImage: quay.io/tripleowallabycentos9/openstack-nova-conductor:current-tripleo
    replicate: 3
    nodeSelector: {}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    debug:
      stopDBSync: False
      stopService: False
      preserveJob: False
  # lets assume in this example that metadata is at cell level
  metadataServiceTemplate:
    cellName: cell2
    secret: osp-secret
    passwordSelectors:
      service: NovaPassword
      # We don't provider the API DB password selector here as this
      # nova-metadata service is expected to run within cell2.
      apiDatabase: null
      #TODO: add it to the definition
      cellDatabase: NovaCell2DatabasePassword
    serviceUser: nova
    keystoneAuthURL: http://keystone-internal-openstack.apps-crc.testing
    apiDatabaseUser: null
    apiDatabaseHostname: null
    cellDatabaseUser: nova
    cellDatabaseHostname: default-security-context
    customServiceConfig: >
      # service config customization
      [DEFAULT]
      debug=True
      [api]
      # make sure this is in sync with the fact that this nova-metadata
      # service is expected to run on the cell level
      local_metadata_per_cell = True
    defaultConfigOverwrite:
      logging.conf: >
        # my custom logging configuration
    # TODO: what is the name of the container for metadata?
    containerImage: quay.io/tripleowallabycentos9/openstack-nova-metadata-api:current-tripleo
    replicate: 3
    nodeSelector: {}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    debug:
      # TODO: nova-metadata wont run dbsync, should we stop using a common
      # Debug struct?
      stopDBSync: False
      stopService: False
      preserveJob: False
  noVNCProxyServiceTemplate:
    CellName: cell2
    Secret: osp-secret
    passwordSelectors:
      service: NovaPassword
      apiDatabase: null
      apiMessageBus: null
      cellDatabase: NovaCell2DatabasePassword
      cellMessageBus: NovaCell2MessageBusPassword
    serviceUser: nova
    keystoneAuthURL: http://keystone-internal-openstack.apps-crc.testing
    apiDatabaseUser: null
    apiDatabaseHostname: null
    apiMessageBusUser: null
    apiMessageBusHostname: null
    cellDatabaseUser: nova
    cellDatabaseHostname: openstack
    cellMessageBusUser: nova
    cellMessageBusHostname: default-security-context
    customServiceConfig: >
      # service config customization
      [DEFAULT]
      debug=True
    defaultConfigOverwrite:
      logging.conf: >
      # my custom logging configuration
    containerImage: quay.io/tripleowallabycentos9/openstack-nova-novncproxy:current-tripleo
    replicate: 3
    nodeSelector: {}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    debug:
      stopDBSync: False
      stopService: False
      preserveJob: False







