
- name: verify podman container volumes
  block:
    - name: get contaienr volumes
      become: true
      ansible.builtin.command: podman inspect {{item.name}} --format \{\{.Mounts\}\}
      register: volumes
    - name: Assert podman container volumes exist
      ansible.builtin.assert:
        that:
          - volumes.rc == 0
          - volumes.stdout_lines | length == 1
          - item.volumes == volumes.stdout
        fail_msg: "Podman container {{ item.name }} does not have the expected volumes {{ item.volumes }} actual {{ volumes.stdout_lines }}"
