
- name: verify systemd service exists
  block:
    - name: Check if systemd file service exists {{ item }}
      become: true
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ item }}.service"
      register: service_exists
    - name: Assert systemd service exists {{ item }}
      ansible.builtin.assert:
        that:
          - service_exists.stat.exists
        fail_msg: "Systemd service file for service {{ item }} does not exist"
    - name: Check if systemd service is enabled {{ item }}
      ansible.builtin.command: systemctl is-enabled {{ item }}
      register: service_enabled
      failed_when: false
      changed_when: false
      ignore_errors: true
    - name: Assert systemd service is enabled {{ item }}
      ansible.builtin.assert:
        that:
          - service_enabled.stdout == "enabled"
        fail_msg: "Systemd service {{ item }} is not enabled"
    - name: Check if systemd service is running {{ item }}
      ansible.builtin.command: systemctl is-active {{ item }}
      register: service_running
      failed_when: false
      changed_when: false
      ignore_errors: true
    - name: Assert systemd service is running {{ item }}
      ansible.builtin.assert:
        that:
          - service_running.stdout == "active"
        fail_msg: "Systemd service {{ item }} is not running"
