---
dependency:
  name: galaxy
verifier:
  name: ansible
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  cachier: machine
  parallel: true
  default_box: 'generic/rocky9'
platforms:
  - name: AEE
    memory: 2048
    cpus: 2
    provider_options:
      cpu_mode: 'host-passthrough'
      nested: true
      machine_type: 'q35'
    groups:
      - oepnshift
  - name: compute-1
    memory: 6000
    cpus: 4
    provider_options:
      cpu_mode: 'host-passthrough'
      nested: true
      machine_type: 'q35'
    groups:
      - compute
provisioner:
  name: ansible
