---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: compute-1
  gather_facts: false
  tasks:
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: test-helpers/verify_dir.yaml
      with_items:
        # common directories
        - "/etc/tmpfiles.d/"
        - "/var/lib/openstack"
        - "/var/lib/openstack/config/containers"
        - "/var/log/containers"
        - "/var/log/containers/stdouts"
        # extrenal deps
        - "/etc/ceph"
        - "/run/openvswitch"
        # libvirt directories
        - "/var/lib/libvirt"
        - "/var/lib/openstack/config/libvirt"
        - "/var/log/containers/libvirt"
        # nova directories
        - "/var/lib/nova"
        - "/var/lib/openstack/config/nova"
        - "/var/lib/_nova_secontext"
        - "/var/lib/nova/instances"
        - "/var/log/containers/nova"
    - name: ensure systemd services are defined and functional
      ansible.builtin.include_tasks: test-helpers/verify_systemd_service.yaml
      with_items:
        - "edpm_libvirt_virtlogd"
        - "edpm_libvirt_virtnodedevd"
        - "edpm_libvirt_virtproxyd"
        - "edpm_libvirt_virtqemud"
        - "edpm_libvirt_virtsecretd"
        - "edpm_nova_compute"
    - name: ensure podman container exists and are running
      ansible.builtin.include_tasks: test-helpers/verify_podman.yaml
      with_items:
        - "libvirt_virtlogd"
        - "libvirt_virtnodedevd"
        - "libvirt_virtproxyd"
        - "libvirt_virtqemud"
        - "libvirt_virtsecretd"
        - "nova_compute"
