apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-0
spec:
  role: edpm-compute
  hostName: edpm-compute-0
  ansibleHost: 192.168.122.100
  node:
    nova: {}
    ansibleVars: |
        ctlplane_ip: 192.168.122.100
        internal_api_ip: 172.17.0.100
        storage_ip: 172.18.0.100
        tenant_ip: 172.19.0.100
        fqdn_internal_api: edpm-compute-0.example.com
  deployStrategy:
    deploy: true
