---
# Note make download_tools and make openstack commands run
# in https://github.com/rdo-infra/review.rdoproject.org-config/blob/master/playbooks/crc/openstack.yaml
# We can override the openstack operator image by defining openstack_img in the zuul job

- hosts: controller
  name: Deploy Openstack Operators
  vars:
    install_yamls_basedir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/install_yamls"
    nova_operator_basedir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/nova-operator"
  tasks:
    - name: Add crc creds
      ansible.builtin.include_role:
        name: rhol_crc
        tasks_from: add_crc_creds

    - name: Disable the openshift-marketplace
      ansible.builtin.shell: |
        oc patch operatorhubs/cluster --type merge --patch '{"spec":{"sources":[{"disabled": true,"name": "redhat-marketplace"}]}}'
      changed_when: true

    - name: Create Openstack Namesapce
      ansible.builtin.shell: |
        oc apply -f "{{ nova_operator_basedir }}/ci/nova-operator-base/namespace.yaml"

    - name: Use OpenStack Namespace
      ansible.builtin.command: oc project openstack
      changed_when: false

    - name: Make sure all Openstack operators are deployed
      ansible.builtin.shell: |
        set -o pipefail && oc get csv -l operators.coreos.com/openstack-operator.openstack --no-headers=true | grep -i "succeeded"
      register: operator_status
      until: operator_status.rc == 0
      changed_when: false
      retries: 30
      delay: 30
