---
- hosts: controller
  name: Deploy Openstack Operators
  vars:
    install_yamls_basedir: "{{ local_install_yamls_basedir | default(ansible_user_dir + '/src/github.com/openstack-k8s-operators/install_yamls')}}"
  tasks:
    - name: Add crc creds
      ansible.builtin.include_role:
        name: rhol_crc
        tasks_from: add_crc_creds
    - name: install tools
      ansible.builtin.command:
        cmd: "make download_tools"
        chdir: "{{install_yamls_basedir}}/devsetup"
    - name: Deploy openstack Operators
      block:
        - name: detect if openstack operator is installed
          ansible.builtin.command:
            cmd: "oc get sub --ignore-not-found=true -n openstack-operators -o name openstack-operator"
          ignore_errors: true
          register: openstack_operator_subscription
        - name: add crc default interface
          when: openstack_operator_subscription.stdout == ""
          ansible.builtin.command:
            cmd: "make crc_attach_default_interface"
            chdir: "{{install_yamls_basedir}}/devsetup"
        - name: Install openstack operator
          when: openstack_operator_subscription.stdout == ""
          ansible.builtin.command:
            cmd: "make openstack"
            chdir: "{{install_yamls_basedir}}"
            creates: "{{install_yamls_basedir}}/out/openstack-operator/openstack/op/*"
          environment:
            OPENSTACK_IMG: "{{ cifmw_operator_build_output.operators['openstack-operator']['image_catalog'] | default(omit) }}"
            OPENSTACK_BUNDLE_IMG: "{{ cifmw_operator_build_output.operators['openstack-operator']['image_bundle'] | default(omit) }}"
            NOVA_IMG: "{{ cifmw_operator_build_output.operators['nova-operator']['image_catalog'] | default(omit) }}"
        - name: Wait for OpenStack subscription creation
          when: openstack_operator_subscription.stdout == ""
          ansible.builtin.command:
            cmd: >-
              oc get sub openstack-operator
              --namespace=openstack-operators
              -o=jsonpath='{.status.installplan.name}'
          register: cifmw_edpm_prepare_wait_installplan_out
          until: cifmw_edpm_prepare_wait_installplan_out.rc == 0 and cifmw_edpm_prepare_wait_installplan_out.stdout != ""
          retries: 30
          delay: 10
        - name: Wait for OpenStack operator to get installed
          when: openstack_operator_subscription.stdout == ""
          ansible.builtin.command:
            cmd: >-
              oc wait InstallPlan {{ cifmw_edpm_prepare_wait_installplan_out.stdout }}
              --namespace=openstack-operators
              --for=jsonpath='{.status.phase}'=Complete --timeout=20m
